# Generated by Django 2.0.7 on 2018-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180717_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
        migrations.RemoveField(
            model_name='option',
            name='is_random',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_random',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_answer',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=20, verbose_name='Duration of quiz in minutes'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_random_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='has_random_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
