# Generated by Django 2.0.7 on 2018-07-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180720_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_answer',
        ),
    ]
