# Generated by Django 2.0.7 on 2018-07-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180720_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
